# Generated by Django 5.0.3 on 2025-06-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название помещения')),
                ('qr_code', models.CharField(max_length=150, unique=True, verbose_name='QR код')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/locations/', verbose_name='QR изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Помещения',
                'ordering': ['name'],
            },
        ),
    ]
