# Generated by Django 5.0.3 on 2025-06-15 08:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('inventory', '__first__'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WrittenOffAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=100, verbose_name='Инвентарный номер')),
                ('asset_name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('book_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Балансовая стоимость')),
                ('responsible', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ответственный')),
                ('location_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Помещение')),
                ('department_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Структурное подразделение')),
                ('year_of_manufacture', models.IntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('photo_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на фото')),
                ('write_off_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата списания')),
            ],
            options={
                'verbose_name': 'Списанное имущество',
                'verbose_name_plural': 'Списанное имущество',
                'ordering': ['-write_off_date'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=100, unique=True, verbose_name='Инвентарный номер')),
                ('asset_name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('book_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Балансовая стоимость')),
                ('responsible', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ответственный')),
                ('year_of_manufacture', models.IntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='assets/', verbose_name='Фото')),
                ('qr_code', models.CharField(blank=True, max_length=150, null=True, verbose_name='QR код')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/assets/', verbose_name='QR изображение')),
                ('is_written_off', models.BooleanField(default=False, verbose_name='Списано')),
                ('write_off_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата списания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='inventory.department', verbose_name='Структурное подразделение')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='locations.location', verbose_name='Помещение')),
            ],
            options={
                'verbose_name': 'Имущество',
                'verbose_name_plural': 'Имущество',
                'ordering': ['inventory_number'],
            },
        ),
    ]
