# Generated by Django 5.0.3 on 2025-06-15 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WrittenOffAsset',
        ),
    ]
