# Generated by Django 5.0.3 on 2025-06-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_delete_writtenoffasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='initial_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
