# Generated by Django 5.0.3 on 2025-06-15 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_asset_initial_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='initial_quantity',
        ),
    ]
