# Generated by Django 5.0.3 on 2025-06-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_remove_asset_initial_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='total_written_off',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
