# Generated by Django 5.0.3 on 2025-06-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_asset_total_written_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='inventory_number',
            field=models.IntegerField(max_length=100, unique=True, verbose_name='Инвентарный номер'),
        ),
    ]
