# Generated by Django 5.0.3 on 2025-06-15 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Структурное подразделение',
                'verbose_name_plural': 'Структурные подразделения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('inventory_type', models.CharField(choices=[('planned', 'Плановая'), ('unplanned', 'Внеплановая')], default='unplanned', max_length=10, verbose_name='Тип инвентаризации')),
                ('status', models.CharField(choices=[('active', 'Активная'), ('completed', 'Завершена')], default='active', max_length=10, verbose_name='Статус')),
                ('date_completed', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventories', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='inventory.department', verbose_name='Структурное подразделение')),
            ],
            options={
                'verbose_name': 'Инвентаризация',
                'verbose_name_plural': 'Инвентаризации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.IntegerField(default=0, verbose_name='Общее количество')),
                ('scanned_quantity', models.IntegerField(default=0, verbose_name='Отсканировано')),
                ('inventory_status', models.CharField(choices=[('pending', 'Ожидает проверки'), ('completed', 'Проверено')], default='pending', max_length=10, verbose_name='Статус')),
                ('last_scanned', models.DateTimeField(blank=True, null=True, verbose_name='Последнее сканирование')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='assets.asset', verbose_name='Имущество')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='inventory.inventory', verbose_name='Инвентаризация')),
            ],
            options={
                'verbose_name': 'Элемент инвентаризации',
                'verbose_name_plural': 'Элементы инвентаризации',
                'unique_together': {('inventory', 'asset')},
            },
        ),
    ]
